export const links = {
    domain: "https://catewebs.vercel.app",
    github: "https://github.com/elizabthpazp/catewebs",
    githubBlog: "https://github.com/elizabthpazp/blog",
    username: "CateWebs",
    telegram: "https://t.me/elizabthpazp",
    instagram: "https://instagram.com/cate_webs/",
    tiktok: "https://www.tiktok.com/@elizabthpazp",
    linkedin: "https://www.linkedin.com/in/elizabeth-de-la-paz-portal-4b864b209",
    discord: "https://discord.com/users/1062024233577893918",
    facebook: "https://www.facebook.com/catewebsdesign", 
    whatsapp: "https://api.whatsapp.com/send?phone=+5353152699&text=Hola%21%!",
    logo: "/logo.png",
    icon: "/favicons/favicon.ico",
    iconSpain: "/spain.webp",
    iconUsa: "/usa.webp",
    iconLike: "/icons/amor.png",
    tiendaOnline: "/tienda online.png",
    marketing:"/marketing digital.png",
    seo: "/SEO.jpg",
    desarrolloweb: "/diseno web.png",
    disenno: "/diseno.jpg",
    sistemas: "/diseno sistema.png"
} as const
 